esphome:
  name: jc3248_display

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

output:
  - platform: gpio
    pin: 21
    id: backlight_output

light:
  - platform: binary
    name: "Backlight"
    output: backlight_output
    restore_mode: ALWAYS_ON

# ========== NORMAL SPI (NICHT QUAD!)
spi:
  clk_pin: 18
  mosi_pin: 13
  miso_pin: 19

# ========== DISPLAY
display:
  - platform: ili9xxx
    model: ILI9341
    invert_colors: false
    cs_pin: 5
    dc_pin: 4
    dimensions:
      width: 320
      height: 240
    rotation: 90
    lambda: |-
      it.printf(40, 100, id(font1), Color(255, 255, 255), "Hallo ESP32!");

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 40